### ISSUE TITLE
setup foreman_wds

### ISSUE THREAD

**Issue by tomabg** [ananace/foreman_wds#4]
Hi,

i have managed to install the forman_wds plugin.
Now i see the Infrastruktur-->WDS servers menü

When i click on it i get following error:
 PG::UndefinedTable: ERROR: relation "wds_servers" does not exist LINE 1: SELECT "wds_servers".* FROM "wds_servers" ORDER BY wds_serv... ^ : SELECT "wds_servers".* FROM "wds_servers" ORDER BY wds_servers.name LIMIT $1 OFFSET $2

Are there further steps needed to add a wds server to database? maybe inside a configfile?

best regards
Thomas

**Comment by ananace** [comment]
Did you run `rake db:migrate` after adding the plugin? (`foreman-rake` if you're using EL)

**Comment by tomabg** [comment]
many thanks for the hints its now working means i can setting up a wds server

Thomas
